In [1]:
zip_path = "/content/drive/MyDrive/AirBnB Project.zip"

In [2]:
!unzip -q "/content/drive/MyDrive/AirBnB Project.zip" -d "/content/data"

In [3]:
import pandas as pd

# Listings Data

In [4]:
df_listings_data = pd.read_csv("/content/data/AirBnB Project/listingsdata.csv")

df_listings_data.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,13913,https://www.airbnb.com/rooms/13913,20250914034649,2025-09-16,city scrape,Holiday London DB Room Let-on going,My bright double bedroom with a large window h...,Finsbury Park is a friendly melting pot commun...,https://a0.muscache.com/pictures/miso/Hosting-...,54730,...,4.87,4.78,4.78,NaN,f,2,1,1,0,0.30
1,15400,https://www.airbnb.com/rooms/15400,20250914034649,2025-09-16,city scrape,Bright Chelsea Apartment. Chelsea!,Lots of windows and light. St Luke's Gardens ...,It is Chelsea.,https://a0.muscache.com/pictures/428392/462d26...,60302,...,4.84,4.93,4.74,NaN,f,1,1,0,0,0.51
2,17402,https://www.airbnb.com/rooms/17402,20250914034649,2025-09-16,city scrape,Very Central Modern 3-Bed/2 Bath By Oxford St W1,"You'll have a great time in this beautiful, cl...","Fitzrovia is a very desirable trendy, arty and...",https://a0.muscache.com/pictures/39d5309d-fba7...,67564,...,4.72,4.89,4.61,NaN,f,2,2,0,0,0.32
3,24328,https://www.airbnb.com/rooms/24328,20250914034649,2025-09-18,previous scrape,Battersea live/work artist house,"Artist house by SW Battersea Park, bright high...","- Battersea is a quiet family area, easy acces...",https://a0.muscache.com/pictures/9194b40f-c627...,41759,...,4.93,4.60,4.65,NaN,f,1,1,0,0,0.53
4,36274,https://www.airbnb.com/rooms/36274,20250914034649,2025-09-15,city scrape,Bright 1 bedroom apt off brick lane in Shoreditch,*Update June '25- Pump Installed to improve wa...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,133271,...,4.46,4.85,4.54,NaN,t,2,2,0,0,0.09

In [5]:
df_listings_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96871 entries, 0 to 96870
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            96871 non-null  int64
 1   listing_url                                   96871 non-null  object
 2   scrape_id                                     96871 non-null  int64
 3   last_scraped                                  96871 non-null  object
 4   source                                        96871 non-null  object
 5   name                                          96871 non-null  object
 6   description                                   94421 non-null  object
 7   neighborhood_overview                         41208 non-null  object
 8   picture_url                                   96865 non-null  object
 9   host_id                                       96871 non-null  int64
 10  host_url                                      96871 non-null  object
 11  host_name                                     96828 non-null  object
 12  host_since                                    96830 non-null  object
 13  host_location                                 73100 non-null  object
 14  host_about                                    49833 non-null  object
 15  host_response_time                            65164 non-null  object
 16  host_response_rate                            65164 non-null  object
 17  host_acceptance_rate                          69111 non-null  object
 18  host_is_superhost                             95105 non-null  object
 19  host_thumbnail_url                            96830 non-null  object
 20  host_picture_url                              96830 non-null  object
 21  host_neighbourhood                            45850 non-null  object
 22  host_listings_count                           96830 non-null  float64
 23  host_total_listings_count                     96830 non-null  float64
 24  host_verifications                            96830 non-null  object
 25  host_has_profile_pic                          96830 non-null  object
 26  host_identity_verified                        96830 non-null  object
 27  neighbourhood                                 41209 non-null  object
 28  neighbourhood_cleansed                        96871 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      96871 non-null  float64
 31  longitude                                     96871 non-null  float64
 32  property_type                                 96871 non-null  object
 33  room_type                                     96871 non-null  object
 34  accommodates                                  96871 non-null  int64
 35  bathrooms                                     62025 non-null  float64
 36  bathrooms_text                                96718 non-null  object
 37  bedrooms                                      84096 non-null  float64
 38  beds                                          61951 non-null  float64
 39  amenities                                     96871 non-null  object
 40  price                                         61963 non-null  object
 41  minimum_nights                                96871 non-null  int64
 42  maximum_nights                                96871 non-null  int64
 43  minimum_minimum_nights                        96868 non-null  float64
 44  maximum_minimum_nights                        96868 non-null  float64
 45  minimum_maximum_nights                        96868 non-null  float64
 46  maximum_maximum_nights                        96868 non-null  float64
 47  minimum_nights_avg_ntm                        96871 non-null  float64
 48  maximum_nights_avg_ntm                        96871 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              92622 non-null  object
 51  availability_30                               96871 non-null  int64
 52  availability_60                               96871 non-null  int64
 53  availability_90                               96871 non-null  int64
 54  availability_365                              96871 non-null  int64
 55  calendar_last_scraped                         96871 non-null  object
 56  number_of_reviews                             96871 non-null  int64
 57  number_of_reviews_ltm                         96871 non-null  int64
 58  number_of_reviews_l30d                        96871 non-null  int64
 59  availability_eoy                              96871 non-null  int64
 60  number_of_reviews_ly                          96871 non-null  int64
 61  estimated_occupancy_l365d                     96871 non-null  int64
 62  estimated_revenue_l365d                       61963 non-null  float64
 63  first_review                                  72749 non-null  object
 64  last_review                                   72749 non-null  object
 65  review_scores_rating                          72749 non-null  float64
 66  review_scores_accuracy                        72734 non-null  float64
 67  review_scores_cleanliness                     72740 non-null  float64
 68  review_scores_checkin                         72706 non-null  float64
 69  review_scores_communication                   72729 non-null  float64
 70  review_scores_location                        72705 non-null  float64
 71  review_scores_value                           72705 non-null  float64
 72  license                                       0 non-null      float64
 73  instant_bookable                              96871 non-null  object
 74  calculated_host_listings_count                96871 non-null  int64
 75  calculated_host_listings_count_entire_homes   96871 non-null  int64
 76  calculated_host_listings_count_private_rooms  96871 non-null  int64
 77  calculated_host_listings_count_shared_rooms   96871 non-null  int64
 78  reviews_per_month                             72749 non-null  float64
dtypes: float64(25), int64(20), object(34)
memory usage: 58.4+ MB

In [36]:
df_listings_data.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [6]:
df_listings_data.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,9.687100e+04,9.687100e+04,9.687100e+04,96830.000000,96830.000000,0.0,96871.000000,96871.000000,96871.000000,62025.00000,...,72706.000000,72729.000000,72705.000000,72705.000000,0.0,96871.000000,96871.000000,96871.000000,96871.000000,72749.000000
mean,6.894448e+17,2.025091e+13,2.144494e+08,50.088991,80.305246,NaN,51.509740,-0.127638,3.326228,1.35555,...,4.790344,4.812270,4.729839,4.616202,NaN,16.685499,14.303249,2.325526,0.028553,0.990334
std,5.941222e+17,2.460560e+01,2.196053e+08,399.405694,589.326173,NaN,0.049067,0.101112,2.078605,0.72077,...,0.430135,0.425909,0.409689,0.511816,NaN,53.130290,52.478299,9.623243,0.631484,1.304282
min,1.391300e+04,2.025091e+13,2.594000e+03,1.000000,1.000000,NaN,51.295937,-0.496760,1.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.026058e+07,2.025091e+13,2.726814e+07,1.000000,1.000000,NaN,51.484150,-0.189468,2.000000,1.00000,...,4.760000,4.800000,4.650000,4.500000,NaN,1.000000,0.000000,0.000000,0.000000,0.150000
50%,8.505248e+17,2.025091e+13,1.164321e+08,2.000000,3.000000,NaN,51.513720,-0.127505,2.000000,1.00000,...,4.930000,4.960000,4.850000,4.750000,NaN,2.000000,1.000000,0.000000,0.000000,0.520000
75%,1.254262e+18,2.025091e+13,4.198974e+08,10.000000,14.000000,NaN,51.539108,-0.068316,4.000000,1.50000,...,5.000000,5.000000,5.000000,4.940000,NaN,8.000000,5.000000,1.000000,0.000000,1.290000
max,1.508964e+18,2.025091e+13,7.186905e+08,5469.000000,8769.000000,NaN,51.682630,0.278960,16.000000,26.00000,...,5.000000,5.000000,5.000000,5.000000,NaN,500.000000,499.000000,116.000000,25.000000,36.960000

In [9]:
missing_pct = df_listings_data.isnull().mean() * 100
missing_pct = missing_pct[missing_pct > 0]

print(missing_pct.to_string())

description                       2.529137
neighborhood_overview            57.460953
picture_url                       0.006194
host_name                         0.044389
host_since                        0.042324
host_location                    24.538820
host_about                       48.557360
host_response_time               32.731158
host_response_rate               32.731158
host_acceptance_rate             28.656667
host_is_superhost                 1.823043
host_thumbnail_url                0.042324
host_picture_url                  0.042324
host_neighbourhood               52.669013
host_listings_count               0.042324
host_total_listings_count         0.042324
host_verifications                0.042324
host_has_profile_pic              0.042324
host_identity_verified            0.042324
neighbourhood                    57.459921
neighbourhood_group_cleansed    100.000000
bathrooms                        35.971550
bathrooms_text                    0.157942
bedrooms                         13.187641
beds                             36.047940
price                            36.035552
minimum_minimum_nights            0.003097
maximum_minimum_nights            0.003097
minimum_maximum_nights            0.003097
maximum_maximum_nights            0.003097
calendar_updated                100.000000
has_availability                  4.386246
estimated_revenue_l365d          36.035552
first_review                     24.901157
last_review                      24.901157
review_scores_rating             24.901157
review_scores_accuracy           24.916642
review_scores_cleanliness        24.910448
review_scores_checkin            24.945546
review_scores_communication      24.921803
review_scores_location           24.946578
review_scores_value              24.946578
license                         100.000000
reviews_per_month                24.901157

# Calender

In [10]:
df_calender = pd.read_csv("/content/data/AirBnB Project/calendar.csv")

df_calender.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1196288722069341420,2025-09-15,f,NaN,NaN,1,1125
1,1196288722069341420,2025-09-16,f,NaN,NaN,1,1125
2,1196288722069341420,2025-09-17,f,NaN,NaN,1,1125
3,1196288722069341420,2025-09-18,f,NaN,NaN,1,1125
4,1196288722069341420,2025-09-19,f,NaN,NaN,1,1125

In [11]:
df_calender.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35357974 entries, 0 to 35357973
Data columns (total 7 columns):
 #   Column          Dtype
---  ------          -----
 0   listing_id      int64
 1   date            object
 2   available       object
 3   price           float64
 4   adjusted_price  float64
 5   minimum_nights  int64
 6   maximum_nights  int64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.8+ GB

In [37]:
df_calender.columns

Index(['listing_id', 'date', 'available', 'price', 'adjusted_price',
       'minimum_nights', 'maximum_nights'],
      dtype='object')

In [12]:
df_calender.describe()

         listing_id  price  adjusted_price  minimum_nights  maximum_nights
count  3.535797e+07    0.0             0.0    3.535797e+07    3.535797e+07
mean   6.894452e+17    NaN             NaN    6.263561e+00    2.921079e+05
std    5.941191e+17    NaN             NaN    2.442387e+01    2.483581e+07
min    1.391300e+04    NaN             NaN    1.000000e+00    1.000000e+00
25%    3.026024e+07    NaN             NaN    1.000000e+00    9.000000e+01
50%    8.505248e+17    NaN             NaN    2.000000e+00    3.650000e+02
75%    1.254268e+18    NaN             NaN    4.000000e+00    1.125000e+03
max    1.508964e+18    NaN             NaN    1.125000e+03    2.147484e+09

In [13]:
missing_pct1 = df_calender.isnull().mean() * 100
missing_pct1 = missing_pct1[missing_pct1 > 0]

print(missing_pct1.to_string())

price             100.0
adjusted_price    100.0

# Reviews Data

In [14]:
df_reviews_data = pd.read_csv("/content/data/AirBnB Project/reviewsdata.csv")

df_reviews_data.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,13913,80770,2010-08-18,177109,Michael,My girlfriend and I hadn't known Alina before ...
1,13913,367568,2011-07-11,19835707,Mathias,Alina was a really good host. The flat is clea...
2,13913,529579,2011-09-13,1110304,Kristin,Alina is an amazing host. She made me feel rig...
3,13913,595481,2011-10-03,1216358,Camilla,"Alina's place is so nice, the room is big and ..."
4,13913,612947,2011-10-09,490840,Jorik,"Nice location in Islington area, good for shor..."

In [16]:
df_reviews_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2097996 entries, 0 to 2097995
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   listing_id     int64
 1   id             int64
 2   date           object
 3   reviewer_id    int64
 4   reviewer_name  object
 5   comments       object
dtypes: int64(3), object(3)
memory usage: 96.0+ MB

In [38]:
df_reviews_data.columns

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='object')

In [17]:
df_reviews_data.describe()

         listing_id            id   reviewer_id
count  2.097996e+06  2.097996e+06  2.097996e+06
mean   3.572207e+17  7.776855e+17  1.968301e+08
std    4.905399e+17  5.533266e+17  1.875552e+08
min    1.391300e+04  2.103200e+04  4.400000e+01
25%    1.581313e+07  5.707448e+08  4.043916e+07
50%    3.798997e+07  9.259551e+17  1.279123e+08
75%    8.332622e+17  1.261510e+18  3.257543e+08
max    1.508900e+18  1.512348e+18  7.188301e+08

In [18]:
missing_pct2 = df_reviews_data.isnull().mean() * 100
missing_pct2 = missing_pct2[missing_pct2 > 0]

print(missing_pct2.to_string())

reviewer_name    0.000095
comments         0.009581

# Listings Info

In [19]:
df_listings_info = pd.read_csv("/content/data/AirBnB Project/listings.csv")

df_listings_info.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,13913,Holiday London DB Room Let-on going,54730,Alina,NaN,Islington,51.56861,-0.11270,Private room,70.0,1,55,2025-08-21,0.30,2,331,10,NaN
1,15400,Bright Chelsea Apartment. Chelsea!,60302,Philippa,NaN,Kensington and Chelsea,51.48780,-0.16813,Entire home/apt,149.0,4,97,2025-04-05,0.51,1,199,1,NaN
2,17402,Very Central Modern 3-Bed/2 Bath By Oxford St W1,67564,Liz,NaN,Westminster,51.52195,-0.14094,Entire home/apt,411.0,3,56,2024-02-19,0.32,2,80,0,NaN
3,24328,Battersea live/work artist house,41759,Joe,NaN,Wandsworth,51.47072,-0.16266,Entire home/apt,NaN,7,95,2025-07-05,0.53,1,294,1,NaN
4,36274,Bright 1 bedroom apt off brick lane in Shoreditch,133271,Hendryks,NaN,Tower Hamlets,51.52322,-0.06979,Entire home/apt,210.0,5,15,2025-09-06,0.09,2,323,6,NaN

In [20]:
df_listings_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96871 entries, 0 to 96870
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              96871 non-null  int64
 1   name                            96871 non-null  object
 2   host_id                         96871 non-null  int64
 3   host_name                       96828 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   96871 non-null  object
 6   latitude                        96871 non-null  float64
 7   longitude                       96871 non-null  float64
 8   room_type                       96871 non-null  object
 9   price                           61963 non-null  float64
 10  minimum_nights                  96871 non-null  int64
 11  number_of_reviews               96871 non-null  int64
 12  last_review                     72749 non-null  object
 13  reviews_per_month               72749 non-null  float64
 14  calculated_host_listings_count  96871 non-null  int64
 15  availability_365                96871 non-null  int64
 16  number_of_reviews_ltm           96871 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(6), int64(7), object(5)
memory usage: 13.3+ MB

In [39]:
df_listings_info.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [22]:
df_listings_info.describe()

,id,host_id,neighbourhood_group,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
count,9.687100e+04,9.687100e+04,0.0,96871.000000,96871.000000,6.196300e+04,96871.000000,96871.000000,72749.000000,96871.000000,96871.000000,96871.000000,0.0
mean,6.894448e+17,2.144494e+08,NaN,51.509740,-0.127638,2.299170e+02,5.440297,21.657627,0.990334,16.685499,144.927429,5.709614,NaN
std,5.941222e+17,2.196053e+08,NaN,0.049067,0.101112,4.437589e+03,23.686681,50.368644,1.304282,53.130290,141.808279,11.996770,NaN
min,1.391300e+04,2.594000e+03,NaN,51.295937,-0.496760,7.000000e+00,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000,NaN
25%,3.026058e+07,2.726814e+07,NaN,51.484150,-0.189468,7.700000e+01,1.000000,1.000000,0.150000,1.000000,0.000000,0.000000,NaN
50%,8.505248e+17,1.164321e+08,NaN,51.513720,-0.127505,1.350000e+02,2.000000,5.000000,0.520000,2.000000,96.000000,0.000000,NaN
75%,1.254262e+18,4.198974e+08,NaN,51.539108,-0.068316,2.210000e+02,4.000000,20.000000,1.290000,8.000000,288.000000,6.000000,NaN
max,1.508964e+18,7.186905e+08,NaN,51.682630,0.278960,1.085147e+06,1125.000000,1902.000000,36.960000,500.000000,365.000000,390.000000,NaN

In [23]:
missing_pct3 = df_listings_info.isnull().mean() * 100
missing_pct3 = missing_pct3[missing_pct3 > 0]

print(missing_pct3.to_string())

host_name                0.044389
neighbourhood_group    100.000000
price                   36.035552
last_review             24.901157
reviews_per_month       24.901157
license                100.000000

## Reviews Info

In [25]:
df_reviews_info = pd.read_csv("/content/data/AirBnB Project/reviews.csv")

df_reviews_info.head()

   listing_id        date
0       13913  2010-08-18
1       13913  2011-07-11
2       13913  2011-09-13
3       13913  2011-10-03
4       13913  2011-10-09

In [26]:
df_reviews_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2097996 entries, 0 to 2097995
Data columns (total 2 columns):
 #   Column      Dtype
---  ------      -----
 0   listing_id  int64
 1   date        object
dtypes: int64(1), object(1)
memory usage: 32.0+ MB

In [40]:
df_reviews_info.columns

Index(['listing_id', 'date'], dtype='object')

In [30]:
(df_reviews_info.isnull().sum()/len(df_reviews_info))*100

listing_id    0.0
date          0.0
dtype: float64

# Neighbourhoods

In [31]:
df_neighbourhoods = pd.read_csv("/content/data/AirBnB Project/neighbourhoods.csv")

df_neighbourhoods.head()

   neighbourhood_group         neighbourhood
0                  NaN  Barking and Dagenham
1                  NaN                Barnet
2                  NaN                Bexley
3                  NaN                 Brent
4                  NaN               Bromley

In [32]:
df_neighbourhoods.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   neighbourhood_group  0 non-null      float64
 1   neighbourhood        33 non-null     object
dtypes: float64(1), object(1)
memory usage: 660.0+ bytes

In [41]:
df_neighbourhoods.columns

Index(['neighbourhood_group', 'neighbourhood'], dtype='object')

In [34]:
(df_neighbourhoods.isnull().sum()/len(df_neighbourhoods))*100

neighbourhood_group    100.0
neighbourhood            0.0
dtype: float64